pipeline {
  agent {
    label 'nodejs'
  }

  stages {
    stage ('Install Dependencies') {
      steps {
        dir ('exchange-cli') {
          sh "npm install --save-dev @types/jest"
        }
      }
    }

    stage ('Build') {
      steps {
        dir ('exchange-cli') {
          sh "npm run build"
        }
      }
    }

    stage ('Unit Tests') {
        steps {
          dir ('exchange-cli') {
            sh "npm run test:unit"
          }
        }
    }
  }
}